Translation suport; use tag content for fallback text
cmrd-senya/markdown-it-html5-embed pull request #7
Opened 2017-11-11 02:19 UTC by eloquence

Instead of hardcoding strings that cannot be overridden by the
user, we're using Markdown-It's environment object to support
translation, either with a built-in very naive function, or
with a user-provided function. The English messages can also
be customized without touching the translation logic.

The transparent content inside <video> and <audio> tags is not
a standard accessibility feature like the ALT text; it is only
shown when the browser cannot play this content at all. The
standard recommendation is to use this text to offer a download
link. See, e.g., the examples in
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

This implementation does so, but it also adds the descriptive
text (if any) for good measure. For backwards compatibility, we
continue to store the descriptive text (or "Untitled ...")
in parsed.title, and it can still be accessed inside the
Handlebars template via {{title}}.

2017-11-12 17:10 UTC, cmrd-senya commented
Thanks for your contribution and for thorough comments!

I see that you didn't add any tests for the translation feature you implemented. Looks like that `markdown-it-testgen` tool doesn't support rendering with `env` parameter. However we can override this with a little hack.

Wouldn't you mind to add some translation tests to this PR?

In order to do that you'll need to create another `describe` block in `test/test.js`, and another fixtures file for the `test/fixtures` folder.

We can override `md.render` function within the `describe` block to set `env` for our test:

```js
  var env = {language: "whatever"};
  md.orig_render = md.render;
  md.render = function (input) {
    return this.orig_render(input, env);
  };

```

2017-11-13 00:04 UTC, eloquence commented
Thanks for the quick response, @cmrd-senya! :) I've added a couple of tests, do these look good to you? (I ran a beautifier on the whole file, hence the changes to object literal formatting. If you strongly prefer the old style I can reformat.)

2017-11-29 21:54 UTC, cmrd-senya requested changes
Your code looks good to me, thanks!

I noted a couple of minor things. Other than that, I'm ready to merge it.

And yes, I prefer the beautyfied code, thanks for taking care of the style!

2017-11-29 21:54 UTC, cmrd-senya commented on README.md
> +The keys you need to support are defined in `/lib.index.js`. You can access the
Nit: it should be `lib/index.js` here

2017-11-29 21:54 UTC, cmrd-senya commented on test/test.js
> +  md.orig_render = md.render;
Nit: though it was my recommendation to write it this way, I would actually prefer to have it in the camel case here to comform the commonly accepted style: `origRender`

2017-12-03 22:46 UTC, eloquence commented
Done :)

2017-12-04 20:53 UTC, cmrd-senya approved these changes

2017-12-04 20:54 UTC, merged

2017-12-04 20:54 UTC, cmrd-senya commented
Merged!

Thank you for your work!